medy can install package

diff --git a/bin/medy b/bin/medy
--- a/bin/medy
+++ b/bin/medy
@@ -95,12 +95,16 @@ function checkpackages {
 }
 
 function get {
-  if is-available "wget"; then
-    command wget "$@" &>/dev/null
+  if is-available "wget" && [ $noisy_view = 1 ]; then
+    command wget "$@"
   # elif is-available "curl"; then
   #   command curl -O "${@:2}"
+  elif is-available "wget" && [ $noisy_view = 0 ]; then
+    command wget "$@" &>/dev/null
   else
-    warn "wget not installed."
+    warn wget is not installed, using lynx as fallback
+    set "${*: -1}"
+    lynx -source "$1" > "${1##*/}"
   fi
 }
 
@@ -125,15 +129,19 @@ function setlab {
     cache="$(cygpath -au "$(awk '/last-cache/ {getline; print $1}' /etc/setup/setup.rc)")"
   fi
 
-  where_mirror $mirror
-  where_dir $cache
+  if [ $noisy_view = 1 ]; then
+    where_mirror $mirror
+    where_dir $cache
+  fi
 
   mkdir -p "$cache/$dir/$arch"
   cd "$cache/$dir/$arch"
   if [ -e setup.ini ]; then
+    export SETUP_INI_FILE_PATH=$cache/$dir/$arch/setup.ini
     return 0
   else
     getsetup
+    export SETUP_INI_FILE_PATH=$cache/$dir/$arch/setup.ini
     return 1
   fi
 }
@@ -247,10 +255,10 @@ function medy-install {
   local script
 
   checkpackages "$@"
-  #setlab
-  noupdate=1
-  getsetup
+  setlab
   echo
+
+  mkdir -p /usr/local/Pharmacy
 
   for pkg do
     local already="$(grep -c "^$pkg " /etc/setup/installed.db)"
@@ -361,8 +369,8 @@ function medy-resume-install {
   # download all
 
   echo "Start downloading..."
-  get -O "$(cat /tmp/medy-downloads)" ||
-  {
+  ${ARIA2C[@]} --input-file /tmp/medy-downloads \
+                 `[ "$(cygwin_arch)" = "x86" ] || echo "--deferred-input"` ||  {
     echo -e "\e[1;34mInterrupted:\e[0m To resume installing, run \"medy resume-install\" ."
     exit 1
   }
@@ -458,14 +466,23 @@ function medy-remove {
 }
 
 function verify-remove {
+  # TODO
+  # avoid duplication in dontremovewithdep
+
   local dontremove=(cygwin coreutils gawk bzip2 tar xz wget aria2 bash)
-  for req in ${dontremove[@]};  do
-    echo $1 $req
-    if [[ $1 = $req ]]; then
-      error "medy cannot remove package $1, skipping"
-      return 1
-    else
-      return 0
+  local dontremovewithdep=()
+
+  for dep in ${dontremove[@]}; do
+    dontremovewithdep+="$(pkg-depends $dep) "
+  done
+
+  remove_skip=0
+  for req in ${dontremovewithdep[@]}; do
+    if [[ $1 = $req ]] && [ $remove_skip = 0 ]; then
+      warn "medy cannot remove package $1, skipping"
+      remove_skip=1
+    elif [ $remove_skip = 0 ]; then
+      remove_skip=0
     fi
   done
 }
@@ -489,17 +506,14 @@ function remove-dep {
       removing=`echo ${REMOVE[@]} | grep -c $p`
       ([ $already -gt 0 ] && [ $removing = 0 ]) || continue
 
-
-      verify-remove $p
-
-      # local dontremove="cygwin coreutils gawk bzip2 tar xz wget aria2 bash"
-      # for req in $dontremove
-      # do
-      #   if [ "$p" = "$req" ]; then
-      #     echo; error "medy cannot remove package $p, exiting"
-      #     exit 1
-      #   fi
-      # done
+      local dontremove="cygwin coreutils gawk bzip2 tar xz wget aria2 bash"
+      for req in $dontremove
+      do
+        if [ "$p" = "$req" ]; then
+          echo; error "medy cannot remove package $p, exiting"
+          exit 1
+        fi
+      done
 
       REMOVE=( ${REMOVE[@]} $p )
       do_remove=1
@@ -550,8 +564,8 @@ function medy-search {
   local pkg
 
   checkpackages "$@"
-  #setlab
-
+  setlab
+  
   for pkg do
     echo ""
     echo "Searching..."
@@ -574,28 +588,28 @@ function medy-update {
   getsetup
 }
 
-function remove-without-resolve-dep {
+function remove-to-upgrade {
   for pkg in $@;
   do
-    verify-remove $pkg && echo Removing: $pkg
+    verify-remove $pkg
+    if [ $remove_skip = 0 ]; then
+      echo Removing: $pkg
 
-    # if [ -e "/etc/preremove/$pkg.sh" ]; then
-    #   "/etc/preremove/$pkg.sh"
-    # fi
+      # if [ -e "/etc/preremove/$pkg.sh" ]; then
+      #   "/etc/preremove/$pkg.sh"
+      # fi
 
-    # gzip -cd "/etc/setup/$pkg.lst.gz" | awk '/[^\/]$/ {print "rm -f \"/" $0 "\""}' | sh
-    # awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}' /etc/setup/installed.db
-    # rm -f "/etc/postinstall/$pkg.sh.done" "/etc/preremove/$pkg.sh" "/etc/setup/$pkg.lst.gz"
-    # mv /etc/setup/installed.db /etc/setup/installed.db-save
-    # mv /tmp/awk.$$ /etc/setup/installed.db
-  
+      # gzip -cd "/etc/setup/$pkg.lst.gz" | awk '/[^\/]$/ {print "rm -f \"/" $0 "\""}' | sh
+      # awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}' /etc/setup/installed.db
+      # rm -f "/etc/postinstall/$pkg.sh.done" "/etc/preremove/$pkg.sh" "/etc/setup/$pkg.lst.gz"
+      # mv /etc/setup/installed.db /etc/setup/installed.db-save
+      # mv /tmp/awk.$$ /etc/setup/installed.db
+    fi
   done
   echo Done.
 }
 
 function medy-upgrade {
-  # TODO
-  # Remove package without resolve dep
 
   setlab
   getsetup
@@ -622,7 +636,7 @@ function medy-upgrade {
     tarcurrent="${infocurrent%.*.*}"
 
     if [ "$tarcurrent" != "$tarbase" ]; then
-      echo "$tarbase => $tarcurrent"
+      echo -e "$tarbase \033[32m==>\033[m $tarcurrent"
       target+="$pkgname "
     fi
   done
@@ -632,8 +646,20 @@ function medy-upgrade {
   if [ $DRY_RUN != 1 ]; then
     echo -e;  ask_user "\033[33mDo you wish upgrade?\033[m" || exit 1
 
-    remove-without-resolve-dep "$(echo ${target[@]})"
+    # backup
+    echo ${target[@]} > $cache/$dir/$arch/medy-update-target.dat
+
+    # TODO
+    # implement resume-upgrade
+
+    echo Start Removing...
+    remove-to-upgrade "$(echo ${target[@]})"
+    echo Start Reinstalling...
     # medy-install "$(echo ${target[@]})"
+
+    if [ $? = 0 ]; then
+      rm $cache/$dir/$arch/medy-update-target.dat
+    fi
   fi
 }
 
@@ -649,15 +675,21 @@ function medy-upgrade-self {
   success "Updated medy"
 }
 
+
+  # ._ _  _  _|
+  # | | |(/_(_|\/
+  #            /
+
+
 medylogo="
-  ._ _  _  _|
-  | | |(/_(_|\/
+  ._ _  _  _\033[31m|\033[m
+\033[31m  | | |\033[m(/_(_\033[31m|\033[m\033[34m\/\033[m
              /
 "
-
 function medy-version {
-  echo "$medylogo"
-  echo "  medy version 0.01"
+  echo -e "$medylogo"
+  echo "  version 0.0.2-alpha(\"holy\"-nightly build)"
+  echo ""
 }
 
 function include {
@@ -669,12 +701,14 @@ function include {
 
 include ./bin/common.sh
 include ./bin/medy-*.sh
+include ./bin/perl-module/*.sh
 
 OPT_FILES=()
 SUBCOMMAND=""
 YES_TO_ALL=false
 force=""
 DRY_RUN=false
+noisy_view=0
 INITIAL_ARGS=( "$@" )
 ARGS=()
 while [ $# -gt 0 ]
@@ -701,13 +735,18 @@ do
       shift
     ;;
 
+    --view|-v)
+      noisy_view=1
+      shift
+    ;;
+
     --help)
-      usage
+      medy-help
       exit 0
     ;;
 
-    --version)
-      version
+    --version|-V)
+      medy-version
       exit 0
     ;;
 
@@ -730,6 +769,13 @@ do
     warning "File $file not found, skipping"
   fi
 done
+
+if [ `cygwin_arch` = "x86" ]; then
+  warning "x86 env detected: aria2 can't use --conditional-get, always download and overwrite"
+  ARIA2C=( "aria2c" "--allow-overwrite=true" )
+else
+  ARIA2C=( "aria2c" "--conditional-get" "--allow-overwrite" )
+fi
 
 function invoke_subcommand {
   local SUBCOMMAND="${@:1:1}"
