fix indent

diff --git a/medy b/medy
--- a/medy
+++ b/medy
@@ -3,19 +3,19 @@
 # apt-cyg: install tool for cygwin similar to debian apt-get
 
 # The MIT License (MIT)
-# 
+#
 # Copyright (c) 2013 Trans-code Design
-# 
+#
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
 # in the Software without restriction, including without limitation the rights
 # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 # copies of the Software, and to permit persons to whom the Software is
 # furnished to do so, subject to the following conditions:
-# 
+#
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
-# 
+#
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
@@ -26,9 +26,9 @@
 #
 
 medylogo="
-  ._ _  _  _|   
-  | | |(/_(_|\/ 
-             /  
+  ._ _  _  _|
+  | | |(/_(_|\/
+             /
 "
 
 medy=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)/$(basename $0)
@@ -123,11 +123,11 @@ function setlab {
   elif [ -e /etc/setup/setup.rc ]; then
     mirror="$(awk '/last-mirror/ {getline; print $1}' /etc/setup/setup.rc)"
   fi
-  
+
   dir="$(encode_mirror_url "$mirror/")"
 
   if [ -e /etc/setup/last-cache ]; then
-    cache="$(cygpath -au "$(head -1 /etc/setup/last-mirror)")"    
+    cache="$(cygpath -au "$(head -1 /etc/setup/last-mirror)")"
   elif [ -e /etc/setup/setup.rc ]; then
     cache="$(cygpath -au "$(awk '/last-cache/ {getline; print $1}' /etc/setup/setup.rc)")"
   fi
@@ -188,7 +188,8 @@ YES_TO_ALL=false
 force=""
 INITIAL_ARGS=( "$@" )
 ARGS=()
-while [ $# -gt 0 ]; do
+while [ $# -gt 0 ]
+do
   case "$1" in
 
     --force)
@@ -229,7 +230,8 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-for file in "${OPT_FILES[@]}"; do
+for file in "${OPT_FILES[@]}"
+do
   if [ -f "$file" ]; then
     readarray -t -O ${#ARGS[@]} ARGS < "$file"
   else
@@ -238,8 +240,9 @@ for file in "${OPT_FILES[@]}"; do
 done
 
 function ask_user {
-  
-  while true; do
+
+  while true
+  do
     [ -n "$2" ] && { local pmt="$2"; local def=; }
     [ -n "$2" ] || { local pmt="y/n";local def=; }
     [ $YES_TO_ALL = 1 ] && { local RPY=Y;local def=Y; }
@@ -310,7 +313,7 @@ function medy-info {
   echo "$info_require"
   echo -e "\033[35;4m Version \033[m"""
   echo "$info_version"
-  
+
   echo -e "\033[35;4m Status \033[m"""
   grep "$1" /etc/setup/installed.db &> /dev/null
   if [ $? -eq 0 ]; then
@@ -321,49 +324,48 @@ function medy-info {
 }
 
 function medy-install {
+  local pkg
+  local script
 
-    local pkg
-    local script
+  checkpackages "$@"
+  establish_lab
+  noupdate=1
+  getsetup
+  echo
 
-    checkpackages "$@"
-    establish_lab
-    noupdate=1
-    getsetup
-    echo
-    
-    for pkg do
-      local already="$(grep -c "^$pkg " /etc/setup/installed.db)"
-      if [ $already -ge 1 ] && [ -z $force ]; then
-        warning "Package $pkg is already installed, skipping"
-        continue
-      fi
-      CURRENT="${CURRENT[@]} $pkg"
-    done
+  for pkg do
+    local already="$(grep -c "^$pkg " /etc/setup/installed.db)"
+    if [ $already -ge 1 ] && [ -z $force ]; then
+      warning "Package $pkg is already installed, skipping"
+      continue
+    fi
+    CURRENT="${CURRENT[@]} $pkg"
+  done
 
-    [ -f /tmp/medy-packages ] && {
-      warn "Interrupted resolving deps detected, ignoring."
-      rm /tmp/medy-*
-    }
+  [ -f /tmp/medy-packages ] && {
+    warn "Interrupted resolving deps detected, ignoring."
+    rm /tmp/medy-*
+  }
 
-    echo -n "Resolving dependencies..."
-    
-    resolve_deps
-        
-    RESUME_INSTALL=0
-    medy-resume-install
+  echo -n "Resolving dependencies..."
+
+  resolve_deps
+
+  RESUME_INSTALL=0
+  medy-resume-install
 }
 
 function resolve_deps {
-
-    while true ; do
-
+  while true
+  do
     echo -n "."
     pkgs=${CURRENT[@]}
     CURRENT=""
     hasdeps=0
 
-        
-    for pkg in $pkgs; do
+
+    for pkg in $pkgs
+    do
 
       [ -f /tmp/medy-packages ] && {
         local installing="$( grep -c "$pkg" /tmp/medy-packages)"
@@ -371,7 +373,7 @@ function resolve_deps {
       }
 
       # look for package and save desc file
- 
+
       mkdir -p "release/$pkg"
       awk > "release/$pkg/desc" -v package=`echo $pkg` \
         'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
@@ -384,7 +386,7 @@ function resolve_deps {
         rm /tmp/medy-* 2> /dev/null
         exit 1
       fi
-     
+
       # queue current package
 
       local install="$(awk '/^install: / { print $2; exit }' "release/$pkg/desc")"
@@ -392,16 +394,17 @@ function resolve_deps {
       echo "  dir=release/$pkg" >> /tmp/medy-downloads
       echo $pkg >> /tmp/medy-packages
       hasdeps=1
-      
+
       # resolve dependencies
 
       local requires="$(grep "^requires: " "release/$pkg/desc" | sed -re 's/^requires: *(.*[^ ]) */\1/g' -e 's/ +/ /g')"
 
       local warn=0
-      
+
       if [ -n "$requires" ]; then
-        for package in $requires; do
-          local already="$(grep -c "$package " /etc/setup/installed.db)" 
+        for package in $requires
+        do
+          local already="$(grep -c "$package " /etc/setup/installed.db)"
           if [ $already = 0 ]; then
             CURRENT=( ${CURRENT[@]} $package )
           fi
@@ -414,90 +417,93 @@ function resolve_deps {
         exit 1
       fi
     done
-    
+
     # tailcall
 
     [ $hasdeps = 0 ] && break;
-    done
+  done
 }
 
 function medy-resume-install {
+  echo; echo
+  if [ ! -f "/tmp/medy-packages" ]; then
+    echo "Nothing to install, exiting"
+    exit 0
+  fi
 
-    echo; echo
-    if [ ! -f "/tmp/medy-packages" ]; then
-      echo "Nothing to install, exiting"
-      exit 0
-    fi
-      
-    echo "Following packages will be installed:"
-    for p in $( cat /tmp/medy-packages ); do
-      echo -n $p " "
+  echo "Following packages will be installed:"
+  for p in $( cat /tmp/medy-packages )
+  do
+    echo -n $p " "
+  done
+  echo; ask_user "Do you wish to continue?" || quit
+
+  [ $RESUME_INSTALL = 0 ] || setlab
+
+  # download all
+
+  echo "Start downloading..."
+  get -O "$(cat /tmp/medy-downloads)" ||
+  {
+    echo -e "\e[1;34mInterrupted:\e[0m To resume installing, run \"medy resume-install\" ."
+    exit 1
+  }
+
+  # unpack all
+
+  for pkg in $( cat /tmp/medy-packages )
+  do
+
+    install="$(awk '/^install: / { print $2; exit }' "release/$pkg/desc")"
+    file="$(basename "$install")"
+    cd "release/$pkg"
+
+    # check the sha512
+
+    while true
+    do
+      local digest="$(awk '/^install: / { print $4; exit }' "desc")"
+      local digactual="$(sha512sum $file | awk '{print $1}')"
+      if [ "$digest" != "$digactual" ]; then
+        error "SHA512 sum did not match, retry downloading..."
+        aria2c $mirror/$install
+      else break; fi
     done
-    echo; ask_user "Do you wish to continue?" || quit
 
-    [ $RESUME_INSTALL = 0 ] || setlab
-    
-    # download all
-    
-    echo "Start downloading..."
-    get -O "$(cat /tmp/medy-downloads)" || 
-    {
-      echo -e "\e[1;34mInterrupted:\e[0m To resume installing, run \"medy resume-install\" ."
-      exit 1
-    }
+    echo "Unpacking: $pkg"
+    tar > "/etc/setup/$pkg.lst" xvf "$file" -C /
+    gzip -f "/etc/setup/$pkg.lst"
+    cd ../..
 
-    # unpack all
+    # update the package database
 
-    for pkg in $( cat /tmp/medy-packages ); do
-    
-      install="$(awk '/^install: / { print $2; exit }' "release/$pkg/desc")"
-      file="$(basename "$install")"
-      cd "release/$pkg"
-      
-      # check the sha512
+    awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
+      '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
+      END{if (ins != 1) print pkg " " bz " 0"}' \
+      /etc/setup/installed.db
+    mv /etc/setup/installed.db /etc/setup/installed.db-save
+    mv /tmp/awk.$$ /etc/setup/installed.db
+  done
 
-      while true; do
-        local digest="$(awk '/^install: / { print $4; exit }' "desc")"
-        local digactual="$(sha512sum $file | awk '{print $1}')"
-        if [ "$digest" != "$digactual" ]; then
-          error "SHA512 sum did not match, retry downloading..."
-          aria2c $mirror/$install
-        else break; fi
-      done
-      
-      echo "Unpacking: $pkg"
-      tar > "/etc/setup/$pkg.lst" xvf "$file" -C /
-      gzip -f "/etc/setup/$pkg.lst"
-      cd ../..
-    
-      # update the package database
+  # run all postinstall scripts
 
-      awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
-        '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
-        END{if (ins != 1) print pkg " " bz " 0"}' \
-        /etc/setup/installed.db
-      mv /etc/setup/installed.db /etc/setup/installed.db-save
-      mv /tmp/awk.$$ /etc/setup/installed.db
+  local pis="$(ls /etc/postinstall/*.sh 2>/dev/null | wc -l)"
+  if [ $pis -gt 0 ]; then
+    echo Running postinstall scripts...
+    for script in /etc/postinstall/*.sh
+    do
+      $script
+      mv $script $script.done
     done
-    
-    # run all postinstall scripts
-    
-    local pis="$(ls /etc/postinstall/*.sh 2>/dev/null | wc -l)"
-    if [ $pis -gt 0 ]; then
-      echo Running postinstall scripts...
-      for script in /etc/postinstall/*.sh; do
-        $script
-        mv $script $script.done
-      done
-    fi
-    quit
+  fi
+  quit
 }
 
 function quit {
-    echo "Removing tmp files..."
-    rm /tmp/medy-*
-    echo Done.
-    exit
+  echo "Removing tmp files..."
+  rm /tmp/medy-*
+  echo Done.
+  exit
 }
 
 function medy-remove {
@@ -511,7 +517,8 @@ function medy-remove {
     echo
 
     CURRENT=""
-    for pkg in $@; do
+    for pkg in $@
+    do
       if [ ! -e "/etc/setup/$pkg.lst.gz" -a -z "$force" ]; then
         echo Package manifest missing, cannot remove $pkg.
         continue
@@ -525,76 +532,80 @@ function medy-remove {
 }
 
 function remove-dep {
-    local pkg
-    REMOVE=""
-    do_remove=0
+  local pkg
+  REMOVE=""
+  do_remove=0
 
-    echo -n Resolving dependencies...
+  echo -n Resolving dependencies...
 
-    until [ -z $CURRENT ]; do
+  until [ -z $CURRENT ]
+  do
 
-      echo -n .
-      pkgs=${CURRENT[@]}
-      CURRENT=""
+    echo -n .
+    pkgs=${CURRENT[@]}
+    CURRENT=""
 
-      for p in $pkgs; do
+    for p in $pkgs
+    do
 
-        already="$(grep -c "^$p " /etc/setup/installed.db)"
-        removing=`echo ${REMOVE[@]} | grep -c $p`
-        ([ $already -gt 0 ] && [ $removing = 0 ]) || continue
+      already="$(grep -c "^$p " /etc/setup/installed.db)"
+      removing=`echo ${REMOVE[@]} | grep -c $p`
+      ([ $already -gt 0 ] && [ $removing = 0 ]) || continue
 
-        local dontremove="cygwin coreutils gawk bzip2 tar xz wget aria2 bash"
-        for req in $dontremove; do
-            if [ "$p" = "$req" ]; then
-            echo; error "medy cannot remove package $p, exiting"
-            exit 1
-          fi
-        done
-      
-        REMOVE=( ${REMOVE[@]} $p )
-        do_remove=1
+      local dontremove="cygwin coreutils gawk bzip2 tar xz wget aria2 bash"
+      for req in $dontremove
+      do
+        if [ "$p" = "$req" ]; then
+          echo; error "medy cannot remove package $p, exiting"
+          exit 1
+        fi
+      done
 
-        neededby=`awk '
-          /^@ / {
-            pn = $2
-          }
-          $0 ~ "^requires: .*"query {
-            print pn
-          }
-          ' query="$p" setup.ini`
-        
-        for npkg in $neededby; do
-          CURRENT=( ${CURRENT[@]} $npkg )
-        done
+      REMOVE=( ${REMOVE[@]} $p )
+      do_remove=1
 
+      neededby=`awk '
+        /^@ / {
+          pn = $2
+        }
+        $0 ~ "^requires: .*"query {
+          print pn
+        }
+        ' query="$p" setup.ini`
+
+      for npkg in $neededby
+      do
+        CURRENT=( ${CURRENT[@]} $npkg )
       done
     done
+  done
 
-    echo; echo
+  echo; echo
 
-    [ $do_remove = 1 ] || { echo Nothing to remove, exiting; exit; }
+  [ $do_remove = 1 ] || { echo Nothing to remove, exiting; exit; }
 
-    echo Following packages will be removed:
-    echo ${REMOVE[@]}
-    ask_user "Do you wish to continue?" || exit
-    
-    for pkg in ${REMOVE[@]}; do
+  echo Following packages will be removed:
+  echo ${REMOVE[@]}
+  ask_user "Do you wish to continue?" || exit
 
-      echo Removing: $pkg
+  for pkg in ${REMOVE[@]};
+  do
 
-      if [ -e "/etc/preremove/$pkg.sh" ]; then
-        "/etc/preremove/$pkg.sh"
-      fi
-      
-      gzip -cd "/etc/setup/$pkg.lst.gz" | awk '/[^\/]$/ {print "rm -f \"/" $0 "\""}' | sh
-      awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}' /etc/setup/installed.db
-      rm -f "/etc/postinstall/$pkg.sh.done" "/etc/preremove/$pkg.sh" "/etc/setup/$pkg.lst.gz"
-      mv /etc/setup/installed.db /etc/setup/installed.db-save
-      mv /tmp/awk.$$ /etc/setup/installed.db
-    
-    done
-    echo Done.
-    exit
+    echo Removing: $pkg
+
+    if [ -e "/etc/preremove/$pkg.sh" ]; then
+      "/etc/preremove/$pkg.sh"
+    fi
+
+    gzip -cd "/etc/setup/$pkg.lst.gz" | awk '/[^\/]$/ {print "rm -f \"/" $0 "\""}' | sh
+    awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}' /etc/setup/installed.db
+    rm -f "/etc/postinstall/$pkg.sh.done" "/etc/preremove/$pkg.sh" "/etc/setup/$pkg.lst.gz"
+    mv /etc/setup/installed.db /etc/setup/installed.db-save
+    mv /tmp/awk.$$ /etc/setup/installed.db
+
+  done
+  echo Done.
+  exit
 }
 
 function medy-uninstall {
@@ -620,7 +631,7 @@ function medy-upgrade {
   tail -n +2 )"
 
   echo "@ " >> $cache/$dir/$arch/setup.ini
-  
+
   echo -e "\033[36;4mChecking package update...\033[m"
   for acv in $archive;
   do
@@ -632,7 +643,7 @@ function medy-upgrade {
     #   grep 'install: ' | sed -e 's/install: //g' | awk '{print $1}')"
     tarcurrent="$(perl -ne 'print if /^@ $ENV{pkgname}\n/.../^@ /' $cache/$dir/$arch/setup.ini |\
       head -n -1 | sed '/prev/,$d' | grep 'install: ' |\
-      sed -e 's/install: //g' | awk '{print $1}')"     
+      sed -e 's/install: //g' | awk '{print $1}')"
     infocurrent="${tarcurrent##*/}"
     tarcurrent="${infocurrent%.*.*}"
 
@@ -648,7 +659,7 @@ function medy-upgrade {
 
   medy-remove "$(echo ${target[@]})"
   medy-install "$(echo ${target[@]})"
-  
+
 }
 
 function medy-doctor {
@@ -658,15 +669,15 @@ function medy-doctor {
 
 function invoke_subcommand {
 
-    local SUBCOMMAND="${@:1:1}"
-    local ARGS=( "${@:2}" )
-    local ACTION="medy-${SUBCOMMAND:-help}"
-    if type "$ACTION" >& /dev/null; then
-      "$ACTION" "${ARGS[@]}"
-    else
-      error "unknown command: $SUBCOMMAND"
-      exit 1
-    fi
+  local SUBCOMMAND="${@:1:1}"
+  local ARGS=( "${@:2}" )
+  local ACTION="medy-${SUBCOMMAND:-help}"
+  if type "$ACTION" >& /dev/null; then
+    "$ACTION" "${ARGS[@]}"
+  else
+    error "unknown command: $SUBCOMMAND"
+    exit 1
+  fi
 }
 
 invoke_subcommand "$SUBCOMMAND" "${ARGS[@]}"
